version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bot_database
      - DB_USER=bot_user
      - DB_PASSWORD=bot_password
      - BOT_TOKEN=7568482602:AAGuphHfDRxam302BlrVYV4waIBZUImSZec
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: bot_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d  
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"

volumes:
  postgres_data:
